title: The world of Gixx

baseurl: ""

url: "https://gixx-web.com"

facebook_username:

twitter_username:

github_username:

linkedin_username:

future: true

destination: docs

excerpt_separator: <!--more-->

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .jekyll-cache
  - .sass-cache
  - .idea
  - node_modules

env: production

reversed_categories:
  - tutorial

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /:categories/:title

autopages:
  enabled: true
  tags:
    layouts:
      - taglist.html
    title: ''
    permalink: /tags/:tag/
    enabled: true
  categories:
    layouts:
      - categorylist.html
    title: ''
    permalink: /:cat/
    enabled: true
  collections:
    enabled: false

jekyll-archives:
  enabled:
    - month
  layouts:
    month: 'datelist'
  permalinks:
    month: '/archive/:year-:month/'

pagination:
  enabled: true
  per_page: 12
  offset: 0
  permalink: '/page/:num'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

jekyll_tidy:
  exclude: ['robots.txt']
  compress_html: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-archives
  - jekyll-include-cache
  - rouge
  - uglifier
  - jekyll-last-modified-at
  - jekyll-plantuml
  - jekyll-tidy
  - classifier-reborn
  - jekyll-tagging-related_posts
  - jekyll-paginate-v2